#!/bin/bash
set -e

PACKAGE_VERSION=$(sed -n '/Version:/p' DESCRIPTION | sed 's/[^0-9,.]*//g')

echo "Build hook running for version" $PACKAGE_VERSION
docker build \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg VCS_URL=`git config --get remote.origin.url` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION=$PACKAGE_VERSION \
  -t $IMAGE_NAME .
