FROM rocker/r-ver:3.4.0
LABEL maintainer="o2r"
RUN export DEBIAN_FRONTEND=noninteractive; apt-get -y update \
  && apt-get install -y git-core \
	libudunits2-dev
RUN ["install2.r", "graphics", "grDevices", "grid", "here", "Rcpp", "remotes", "units", "utils"]
RUN ["installGithub.r", "r-hub/sysreqs@master", "viking/r-yaml@v2.1.17"]
WORKDIR /payload/
COPY ["package_description/hello.txt", "package_description/hello.txt"]
CMD ["R"]
